### ISSUE TITLE
support order for gear vr

### ISSUE THREAD

**Issue by sebastianandrioli** [DrBeef/Lambda1VR#62] opened 2019-11-03 12:14 UTC
please man add support for gear vr and usb joistick (that you can modify the mapping in config) as the xash brought

**Comment by baggyg** [comment] 2019-11-04 01:05
Duplicate of your #21 issue. Dr Beef already provided an answer:

"Hi

I'm afraid I won't be making any changes to support the GearVR or GO.. there are too many things that would need to be modified/changed to get it working correctly.

If someone else is willing to fork this project and do the necessary changes then I would be happy to accept a pull request. I'll leave this issue open for now in case someone with the necessary skillset sees it.

I'm going to close this.. the problem is that many weapons code relies on the 6DoF controllers.. such as throwing grenades, swinging the crowbar etc. It isn't simply a case of adding in gamepad support, but restoring all the old weapon logic when the gamepad is used.

Someone else is welcome to fork the code and try, but I won't be doing this myself I'm afraid."

**Closed by baggyg** 2019-11-04 01:05 UTC
