### ISSUE TITLE
Half life vr worck in me gear vr

### ISSUE THREAD

**Issue by sebastianandrioli** [DrBeef/Lambda1VR#21] opened 2019-08-02 16:58 UTC
Hi my name is Sebastian.
download lambda 1 vr.apk and install it on my note 8. and it works fine on my gear vr. I only need to edit the buttons on the command of my gear vr (and add support for a USB controller, I use a ps3 navigator)
could someone help me in this modification?
https://youtu.be/uNLkM7IFfJA
https://youtu.be/KoJG7ge-b6E

**Comment by DrBeef** [comment] 2019-08-03 07:27
Hi

I'm afraid I won't be making any changes to support the GearVR or GO.. there are too many things that would need to be modified/changed to get it working correctly.

If someone else is willing to fork this project and do the necessary changes then I would be happy to accept a pull request. I'll leave this issue open for now in case someone with the necessary skillset sees it.

**Comment by sebastianandrioli** [comment] 2019-08-03 09:33
well thank you very much for responding. It's a shame but I know you could help me. I don't know anyone with the ability to do that.

**Comment by DrBeef** [comment] 2019-09-19 11:04
I'm going to close this.. the problem is that many weapons code relies on the 6DoF controllers.. such as throwing grenades, swinging the crowbar etc. It isn't simply a case of adding in gamepad support, but restoring all the old weapon logic when the gamepad is used.

Someone else is welcome to fork the code and try, but I won't be doing this myself I'm afraid.

**Closed by DrBeef** 2019-09-19 11:04 UTC
